image: gitlab.futo.org:5050/polycentric/neopass:ci 

stages:
  - build
  - test
  - format
  - lint

build:
  stage: build
  cache:
    paths: 
      - $CI_PROJECT_DIR/.pub-cache/
      - $CI_PROJECT_DIR/.gradle/
  variables:
    GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle/
    FF_USE_FASTZIP: "true"
    ARTIFACT_COMPRESSION_LEVEL: "fast"
    CACHE_COMPRESSION_LEVEL: "fast"
  script:
    - export PUB_CACHE=$CI_PROJECT_DIR/.pub-cache
    - export PATH="$PATH":"$PUB_CACHE/bin"
    - ./version.sh && cd neopass_flutter && make build-apk
  artifacts:
    paths:
      - neopass_flutter/build/app/outputs/flutter-apk/app-release.apk

test:
  stage: test
  script:
    - ./version.sh && cd neopass_flutter && make test

format:
  stage: format
  script:
    - ./version.sh && cd neopass_flutter && make format

lint:
  stage: lint
  script:
    - ./version.sh && cd neopass_flutter && make lint

