image: ghcr.io/cirruslabs/flutter:3.10.2

stages:
  - build
  - test
  - format
  - lint

build:
  stage: build
  script:
    - cd neopass_flutter && make build-apk
  artifacts:
    paths:
      - neopass_flutter/build/app/outputs/flutter-apk/app-release.apk

test:
  stage: test
  script:
    - cd neopass_flutter && make test

format:
  stage: format
  script:
    - cd neopass_flutter && make format

lint:
  stage: lint
  script:
    - cd neopass_flutter && make lint

